"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    portal_name: "Election Portal",
    election_dates: "Election Dates",
    voter_guide: "Voter Guide",
    polling_stations: "Polling Stations",
    results: "Results",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    logout: "Logout",
    dashboard: "Dashboard",
    voter_services: "Voter Services",
    live_trends: "Live Trends",
    eci_resources: "ECI Resources",
    find_constituency: "Find Constituency",
    search_placeholder: "Enter PIN or Name...",
    lookup_btn: "LOOKUP",
    chat_title: "Bharat Nirvachan AI",
    chat_subtitle: "Official Civic Assistant",
    verified_eci: "Verified by ECI Documents",
    ask_placeholder: "Ask a question...",
    source_eci: "Source: Election Commission of India",
    days_to_election: "Days to Election",
    voting_reminders: "Get Voting Reminders",
    official_links: "Official ECI Links",
    candidates: "Candidates",
    vvpat_simulator: "VVPAT Simulator",
    verify_voter_id: "Verify Voter ID",
    settings: "Settings",
    support: "Support",
    language: "Language",
    suggestion_1: "How to register as a voter?",
    suggestion_2: "What is my constituency?",
    suggestion_3: "Who are the candidates in New Delhi?",
    suggestion_4: "What is a VVPAT machine?",
    system_ready: "System Ready",
    quick_enquiries: "Quick Enquiries",
    chat_error: "Sorry, I'm having trouble connecting right now.",
    verified_eci_title: "Verified ECI Data",
    verified_eci_subtitle: "Direct access to official Election Commission of India portals.",
    official_integration: "Official Integration",
    open_portal: "OPEN OFFICIAL PORTAL",
    eci_disclaimer: "All data linked here is sourced directly from the Election Commission of India (ECI).",
    res_voter_search_title: "Voter Search",
    res_voter_search_desc: "Search your name in the Electoral Roll and find your polling booth.",
    res_candidate_title: "Know Your Candidate",
    res_candidate_desc: "Detailed information about candidates including affidavits and criminal records.",
    res_education_title: "Voter Education",
    res_education_desc: "Learn about the voting process, EVMs, VVPATs and your rights.",
    res_results_title: "Real-time Results",
    res_results_desc: "Access the official election results portal for verified trends.",
    lookup_title: "Find Your Constituency",
    lookup_subtitle: "Enter your PIN code or Constituency name to get official candidate links.",
    lookup_placeholder: "e.g. 110001 or New Delhi",
    constituency_suffix: "Constituency",
    official_document: "Official Document",
    view_affidavits: "View Affidavits",
    candidate_list: "Candidate List",
    know_candidates: "Know Candidates",
    eci_portal_note: "Note: These links will take you to the official ECI portal. Make sure to select the correct phase and election year (2024) once on the site.",
    no_match_title: "No direct match for",
    no_match_subtitle: "But don't worry, you can find it on the official ECI search portal.",
    go_to_official_search: "Official Search",
    welcome_back: "Namaste",
    welcome_subtitle: "Welcome to your personalized election dashboard.",
    national_turnout: "National Turnout",
    total_votes_polled: "Total Votes Polled",
    status: "Status",
    live_trend_analysis: "Live Trend Analysis",
    election_timeline: "Election Timeline",
    live_results: "Live Results",
    need_help: "Need help?",
    ai_help_desc: "Ask our AI assistant about voting rules or candidate details.",
    start_chat: "Start Chat",
    know_candidates_desc: "Review profiles, assets, and promises of candidates in your area.",
    voter_search_desc: "Check your name in the electoral roll and verify your polling station.",
    voter_services_desc: "Register as a new voter, update address, or apply for a replacement card.",
    browse_list: "Browse List",
    search_name: "Search Name",
    days: "Days",
    hours: "Hours",
    minutes: "Mins",
    seconds: "Secs",
    simulator_title: "How to Vote: EVM & VVPAT",
    simulator_desc: "Understand the verification process.",
    evm_unit: "EVM Control Unit",
    vvpat_verifier: "VVPAT Verifier",
    set_as_home: "Set as Home",
    account_settings: "Account Settings",
    manage_profile: "Manage your profile, preferences, and voter information.",
    full_name: "Full Name",
    age: "Age",
    voter_id: "Voter ID",
    home_constituency: "Home Constituency",
    home_state: "Home State",
    save_changes: "Save Changes",
    profile_updated: "Profile updated successfully!",
    lang_regional: "Language & Regional Preferences",
    account_security: "Account Security",
    logout_desc: "Logging out will end your current session. Make sure you have saved your constituency details to receive relevant election notifications.",
    step_register: "Register to Vote",
    step_verify: "Verify Details",
    step_booth: "Find Your Booth",
    step_candidates: "Know Candidates",
    step_vote: "Cast Your Vote",
    assistant_welcome: "Hello! I am your Bharat Nirvachan Assistant. How can I help you today?",
    process_timeline: "Election Process Timeline",
    step_1_title: "1. Voter Registration",
    step_1_desc: "Ensure you are registered on the electoral roll. Use Form 6 for new registration.",
    step_2_title: "2. Identity Verification",
    step_2_desc: "Check your name in the Voter List and ensure you have a valid EPIC card or ID.",
    step_3_title: "3. Locate Polling Station",
    step_3_desc: "Find your assigned polling booth using our map or the ECI portal.",
    step_4_title: "4. Informed Choice",
    step_4_desc: "Read manifestos and affidavits of candidates in your constituency.",
    step_5_title: "5. Polling Day",
    step_5_desc: "Go to your booth, verify your ID, and cast your vote on the EVM machine.",
    learn_more: "Learn More",
    back_to_chat: "Back to Chat",
    start_journey: "Start Voter Journey",
    go_to_registration: "Register Now",
    verify_now: "Verify ID",
    locate_booth: "Locate Booth",
    browse_candidates: "See Candidates",
    how_to_vote: "Watch Tutorial",
    step_status_complete: "Completed",
    step_status_pending: "Action Required"
  },
  hi: {
    portal_name: "चुनाव पोर्टल",
    election_dates: "चुनाव तिथियां",
    voter_guide: "मतदाता मार्गदर्शिका",
    polling_stations: "मतदान केंद्र",
    results: "परिणाम",
    sign_in: "साइन इन करें",
    sign_up: "साइन अप करें",
    logout: "लॉगआउट",
    dashboard: "डैशबोर्ड",
    voter_services: "मतदाता सेवाएं",
    live_trends: "लाइव रुझान",
    eci_resources: "ईसीआई संसाधन",
    find_constituency: "निर्वाचन क्षेत्र खोजें",
    search_placeholder: "पिन या नाम दर्ज करें...",
    lookup_btn: "खोजें",
    chat_title: "भारत निर्वाचन AI",
    chat_subtitle: "आधिकारिक नागरिक सहायक",
    verified_eci: "ईसीआई दस्तावेजों द्वारा सत्यापित",
    ask_placeholder: "एक प्रश्न पूछें...",
    source_eci: "स्रोत: भारत निर्वाचन आयोग",
    days_to_election: "चुनाव के दिन",
    voting_reminders: "मतदान अनुस्मारक प्राप्त करें",
    official_links: "आधिकारिक ईसीआई लिंक",
    candidates: "उम्मीदवार",
    vvpat_simulator: "VVPAT सिम्युलेटर",
    verify_voter_id: "मतदाता आईडी सत्यापित करें",
    settings: "सेटिंग्स",
    support: "सहायता",
    language: "भाषा",
    suggestion_1: "मतदाता के रूप में पंजीकरण कैसे करें?",
    suggestion_2: "मेरा निर्वाचन क्षेत्र क्या है?",
    suggestion_3: "नई दिल्ली में उम्मीदवार कौन हैं?",
    suggestion_4: "VVPAT मशीन क्या है?",
    system_ready: "प्रणाली तैयार है",
    quick_enquiries: "त्वरित पूछताछ",
    chat_error: "क्षमा करें, मुझे अभी जुड़ने में समस्या हो रही है।",
    verified_eci_title: "सत्यापित ईसीआई डेटा",
    verified_eci_subtitle: "भारत निर्वाचन आयोग के आधिकारिक पोर्टल तक सीधी पहुंच।",
    official_integration: "आधिकारिक एकीकरण",
    open_portal: "आधिकारिक पोर्टल खोलें",
    eci_disclaimer: "यहाँ लिंक किया गया सारा डेटा सीधे भारत निर्वाचन आयोग (ECI) से लिया गया है।",
    res_voter_search_title: "मतदाता खोज",
    res_voter_search_desc: "मतदाता सूची में अपना नाम खोजें और अपना मतदान केंद्र ढूंढें।",
    res_candidate_title: "अपने उम्मीदवार को जानें",
    res_candidate_desc: "शपथ पत्र और आपराधिक रिकॉर्ड सहित उम्मीदवारों के बारे में विस्तृत जानकारी।",
    res_education_title: "मतदाता शिक्षा",
    res_education_desc: "मतदान प्रक्रिया, ईवीएम, वीवीपीएटी और अपने अधिकारों के बारे में जानें।",
    res_results_title: "वास्तविक समय परिणाम",
    res_results_desc: "सत्यापित रुझानों के लिए आधिकारिक चुनाव परिणाम पोर्टल पर जाएं।",
    lookup_title: "अपना निर्वाचन क्षेत्र खोजें",
    lookup_subtitle: "आधिकारिक उम्मीदवार लिंक प्राप्त करने के लिए अपना पिन कोड या निर्वाचन क्षेत्र का नाम दर्ज करें।",
    lookup_placeholder: "जैसे 110001 या नई दिल्ली",
    constituency_suffix: "निर्वाचन क्षेत्र",
    official_document: "आधिकारिक दस्तावेज",
    view_affidavits: "शपथ पत्र देखें",
    candidate_list: "उम्मीदवार सूची",
    know_candidates: "उम्मीदवारों को जानें",
    eci_portal_note: "नोट: ये लिंक आपको आधिकारिक ईसीआई पोर्टल पर ले जाएंगे।",
    no_match_title: "के लिए कोई सीधा मिलान नहीं",
    no_match_subtitle: "लेकिन चिंता न करें, आप इसे आधिकारिक ईसीआई खोज पोर्टल पर पा सकते हैं।",
    go_to_official_search: "आधिकारिक खोज पर जाएं",
    welcome_back: "नमस्ते",
    welcome_subtitle: "आपके व्यक्तिगत चुनाव डैशबोर्ड में आपका स्वागत है।",
    national_turnout: "राष्ट्रीय मतदान",
    total_votes_polled: "कुल मतदान",
    status: "स्थिति",
    live_trend_analysis: "लाइव रुझान विश्लेषण",
    election_timeline: "चुनाव समयरेखा",
    live_results: "लाइव परिणाम",
    need_help: "सहायता चाहिए?",
    ai_help_desc: "मतदान नियमों या उम्मीदवार विवरणों के बारे में हमारे एआई सहायक से पूछें।",
    start_chat: "चैट शुरू करें",
    know_candidates_desc: "अपने क्षेत्र के उम्मीदवारों के प्रोफाइल, संपत्ति और वादों की समीक्षा करें।",
    voter_search_desc: "मतदाता सूची में अपना नाम जांचें और अपने मतदान केंद्र को सत्यापित करें।",
    voter_services_desc: "नए मतदाता के रूप में पंजीकरण करें, पता अपडेट करें, या प्रतिस्थापन कार्ड के लिए आवेदन करें।",
    browse_list: "सूची ब्राउज़ करें",
    search_name: "नाम खोजें",
    days: "दिन",
    hours: "घंटे",
    minutes: "मिनट",
    seconds: "सेकंड",
    simulator_title: "वोट कैसे करें: EVM और VVPAT",
    simulator_desc: "सत्यापन प्रक्रिया को समझें।",
    evm_unit: "EVM कंट्रोल यूनिट",
    vvpat_verifier: "VVPAT सत्यापनकर्ता",
    set_as_home: "इसे होम सेट करें",
    start_journey: "मतदाता यात्रा शुरू करें",
    go_to_registration: "अभी पंजीकरण करें",
    verify_now: "आईडी सत्यापित करें",
    locate_booth: "बूथ खोजें",
    browse_candidates: "उम्मीदवार देखें",
    how_to_vote: "ट्यूटोरियल देखें",
    step_status_complete: "पूरा हुआ",
    step_status_pending: "कार्रवाई आवश्यक"
  },
  ta: {
    portal_name: "தேர்தல் போர்டல்",
    election_dates: "தேர்தல் தேதிகள்",
    voter_guide: "வாக்காளர் வழிகாட்டி",
    polling_stations: "வாக்குச்சாவடிகள்",
    results: "முடிவுகள்",
    sign_in: "உள்நுழைக",
    sign_up: "பதிவு செய்க",
    logout: "வெளியேறு",
    dashboard: "டாஷ்போர்டு",
    voter_services: "வாக்காளர் சேவைகள்",
    live_trends: "நேரடி போக்குகள்",
    eci_resources: "ECI ஆதாரங்கள்",
    find_constituency: "தொகுதியைத் தேடு",
    search_placeholder: "பின் அல்லது பெயரை உள்ளிடவும்...",
    lookup_btn: "தேடு",
    chat_title: "பாரத தேர்தல் AI",
    chat_subtitle: "அதிகாரப்பூர்வ குடிமை உதவியாளர்",
    verified_eci: "ECI ஆவணங்களால் சரிபார்க்கப்பட்டது",
    ask_placeholder: "கேள்வி கேளுங்கள்...",
    source_eci: "ஆதாரம்: இந்திய தேர்தல் ஆணையம்",
    days_to_election: "தேர்தல் நாட்கள்",
    voting_reminders: "வாக்குப்பதிவு நினைவூட்டல்களைப் பெறுங்கள்",
    official_links: "அதிகாரப்பூர்வ ECI இணைப்புகள்",
    candidates: "வேட்பாளர்கள்",
    vvpat_simulator: "VVPAT சிமுலேட்டர்",
    verify_voter_id: "வாக்காளர் அடையாளத்தை சரிபார்க்கவும்",
    settings: "அமைப்புகள்",
    support: "ஆதரவு",
    language: "மொழி",
    suggestion_1: "வாக்காளராக பதிவு செய்வது எப்படி?",
    suggestion_2: "எனது தொகுதி எது?",
    suggestion_3: "புது தில்லியில் உள்ள வேட்பாளர்கள் யார்?",
    suggestion_4: "VVPAT இயந்திரம் என்றால் என்ன?",
    system_ready: "அமைப்பு தயார்",
    quick_enquiries: "விரைவான விசாரணைகள்",
    chat_error: "மன்னிக்கவும், எனக்கு இப்போது இணைப்பதில் சிக்கல் உள்ளது.",
    verified_eci_title: "சரிபார்க்கப்பட்ட ECI தரவு",
    verified_eci_subtitle: "இந்திய தேர்தல் ஆணையத்தின் அதிகாரப்பூர்வ போர்ட்டல்களுக்கான நேரடி அணுகல்.",
    official_integration: "அதிகாரப்பூர்வ ஒருங்கிணைப்பு",
    open_portal: "அதிகாரப்பூர்வ போர்ட்டலைத் திற",
    eci_disclaimer: "இங்கே இணைக்கப்பட்டுள்ள அனைத்து தரவுகளும் இந்திய தேர்தல் ஆணையத்திடமிருந்து (ECI) நேரடியாகப் பெறப்படுகின்றன.",
    res_voter_search_title: "வாக்காளர் தேடல்",
    res_voter_search_desc: "வாக்காளர் பட்டியலில் உங்கள் பெயரைத் தேடி, உங்கள் வாக்குச்சாவடியைக் கண்டறியவும்.",
    res_candidate_title: "உங்கள் வேட்பாளரை அறியுங்கள்",
    res_candidate_desc: "வேட்பாளர்கள் பற்றிய விரிவான தகவல்கள்.",
    res_education_title: "வாக்காளர் கல்வி",
    res_education_desc: "வாக்களிக்கும் செயல்முறை மற்றும் உங்கள் உரிமைகள் பற்றி அறியுங்கள்.",
    res_results_title: "நேரடி முடிவுகள்",
    res_results_desc: "அதிகாரப்பூர்வ தேர்தல் முடிவு போர்ட்டலை அணுகவும்.",
    lookup_title: "உங்கள் தொகுதியைக் கண்டறியவும்",
    lookup_subtitle: "அதிகாரப்பூர்வ வேட்பாளர் இணைப்புகளைப் பெற உங்கள் PIN அல்லது தொகுதி பெயரை உள்ளிடவும்.",
    lookup_placeholder: "எ.கா. 110001 அல்லது புது டெல்லி",
    constituency_suffix: "தொகுதி",
    official_document: "அதிகாரப்பூர்வ ஆவணம்",
    view_affidavits: "பிரமாணப் பத்திரங்களைப் பார்க்கவும்",
    candidate_list: "வேட்பாளர் பட்டியல்",
    know_candidates: "வேட்பாளர்களை அறியுங்கள்",
    eci_portal_note: "குறிப்பு: இந்த இணைப்புகள் உங்களை அதிகாரப்பூர்வ ECI போர்ட்டலுக்கு அழைத்துச் செல்லும்.",
    no_match_title: "நேரடிப் பொருத்தம் இல்லை",
    no_match_subtitle: "அதிகாரப்பூர்வ ECI தேடல் போர்ட்டலில் நீங்கள் அதைக் காணலாம்.",
    go_to_official_search: "அதிகாரப்பூர்வ தேடல்",
    welcome_back: "வணக்கம்",
    welcome_subtitle: "உங்கள் தனிப்பயனாக்கப்பட்ட தேர்தல் டாஷ்போர்டிற்கு வரவேற்கிறோம்.",
    national_turnout: "தேசிய வாக்குப்பதிவு",
    total_votes_polled: "பதிவான மொத்த வாக்குகள்",
    status: "நிலை",
    live_trend_analysis: "நேரடி போக்கு பகுப்பாய்வு",
    election_timeline: "தேர்தல் காலவரிசை",
    live_results: "நேரடி முடிவுகள்",
    need_help: "உதவி தேவையா?",
    ai_help_desc: "வாக்களிக்கும் விதிகள் பற்றி எங்கள் AI உதவியாளரிடம் கேளுங்கள்.",
    start_chat: "அரட்டையைத் தொடங்கு",
    know_candidates_desc: "உங்கள் பகுதியில் உள்ள வேட்பாளர்களின் சுயவிவரங்களை மதிப்பாய்வு செய்யவும்.",
    voter_search_desc: "வாக்காளர் பட்டியலில் உங்கள் பெயரைச் சரிபார்க்கவும்.",
    voter_services_desc: "புதிய வாக்காளராகப் பதிவு செய்யுங்கள்.",
    browse_list: "பட்டியலை உலாவுக",
    search_name: "பெயரைத் தேடு",
    days: "நாட்கள்",
    hours: "மணிநேரம்",
    minutes: "நிமிடங்கள்",
    seconds: "வினாடிகள்",
    simulator_title: "வாக்களிப்பது எப்படி: EVM & VVPAT",
    simulator_desc: "சரிபார்ப்பு செயல்முறையைப் புரிந்து கொள்ளுங்கள்.",
    evm_unit: "EVM கட்டுப்பாட்டு அலகு",
    vvpat_verifier: "VVPAT சரிபார்ப்பவர்",
    set_as_home: "முகப்பாக அமை",
    start_journey: "வாக்காளர் பயணத்தைத் தொடங்கு",
    go_to_registration: "இப்போதே பதிவு செய்யுங்கள்",
    verify_now: "ஐடியைச் சரிபார்க்கவும்",
    locate_booth: "பூத்தைக் கண்டறியவும்",
    browse_candidates: "வேட்பாளர்களைப் பார்க்கவும்",
    how_to_vote: "டுடோரியலைப் பாருங்கள்",
    step_status_complete: "முடிந்தது",
    step_status_pending: "நடவடிக்கை தேவை"
  },
  te: {
    portal_name: "ఎన్నికల పోర్టల్",
    election_dates: "ఎన్నికల తేదీలు",
    voter_guide: "ఓటరు గైడ్",
    polling_stations: "పోలింగ్ కేంద్రాలు",
    results: "ఫలితాలు",
    sign_in: "సైన్ ఇన్",
    sign_up: "సైన్ అప్",
    logout: "లాగ్అవుట్",
    dashboard: "డాష్‌బోర్డ్",
    voter_services: "ఓటరు సేవలు",
    live_trends: "లైవ్ ట్రెండ్స్",
    eci_resources: "ECI వనరులు",
    find_constituency: "నియోజకవర్గాన్ని కనుగొనండి",
    search_placeholder: "పిన్ లేదా పేరు నమోదు చేయండి...",
    lookup_btn: "వెతకండి",
    chat_title: "భారత ఎన్నికల AI",
    chat_subtitle: "అధికారిక పౌర సహాయకుడు",
    verified_eci: "ECI పత్రాల ద్వారా ధృవీకరించబడింది",
    ask_placeholder: "ప్రశ్న అడగండి...",
    source_eci: "మూలం: భారత ఎన్నికల సంఘం",
    days_to_election: "ఎన్నికల రోజులు",
    voting_reminders: "ఓటింగ్ రిమైండర్‌లను పొందండి",
    official_links: "అధికారిక ECI లింకులు",
    candidates: "అభ్యర్థులు",
    vvpat_simulator: "VVPAT సిమ్యులేటర్",
    verify_voter_id: "ఓటరు ఐడిని ధృవీకరించండి",
    settings: "సెట్టింగ్‌లు",
    support: "మద్దతు",
    language: "భాష",
    suggestion_1: "ఓటరుగా ఎలా నమోదు చేసుకోవాలి?",
    suggestion_2: "నా నియోజకవర్గం ఏది?",
    suggestion_3: "న్యూఢిల్లీలో అభ్యర్థులు ఎవరు?",
    suggestion_4: "VVPAT యంత్రం అంటే ఏమిటి?",
    system_ready: "వ్యవస్థ సిద్ధంగా ఉంది",
    quick_enquiries: "త్వరిత విచారణలు",
    chat_error: "క్షమించండి, నాకు ఇప్పుడు కనెక్ట్ చేయడంలో సమస్య ఉంది.",
    verified_eci_title: "ధృవీకరించబడిన ECI డేటా",
    verified_eci_subtitle: "భారత ఎన్నికల సంఘం అధికారిక పోర్టల్‌లకు ప్రత్యక్ష ప్రాప్యత.",
    official_integration: "అధికారిక ఏకీకరణ",
    open_portal: "అధికారిక పోర్టల్ తెరవండి",
    eci_disclaimer: "ఇక్కడ లింక్ చేయబడిన మొత్తం డేటా నేరుగా భారత ఎన్నికల సంఘం (ECI) నుండి తీసుకోబడింది.",
    res_voter_search_title: "ఓటరు శోధన",
    res_voter_search_desc: "ఓటర్ల జాబితాలో మీ పేరును వెతకండి.",
    res_candidate_title: "మీ అభ్యర్థిని తెలుసుకోండి",
    res_candidate_desc: "అభ్యర్థుల గురించి వివరణాత్మక సమాచారం.",
    res_education_title: "ఓటరు విద్య",
    res_education_desc: "ఓటింగ్ ప్రక్రియ గురించి తెలుసుకోండి.",
    res_results_title: "నిజ-సమయ ఫలితాలు",
    res_results_desc: "అధికారిక ఎన్నికల ఫలితాల పోర్టల్‌ను సందర్శించండి.",
    lookup_title: "మీ నియోజకవర్గాన్ని కనుగొనండి",
    lookup_subtitle: "అధికారిక అభ్యర్థి లింకులను పొందడానికి మీ పిన్ లేదా నియోజకవర్గం పేరును నమోదు చేయండి.",
    lookup_placeholder: "ఉదా. 110001 లేదా న్యూఢిల్లీ",
    constituency_suffix: "నియోజకవర్గం",
    official_document: "అధికారిక పత్రం",
    view_affidavits: "అఫిడవిట్లను చూడండి",
    candidate_list: "అభ్యర్థుల జాబితా",
    know_candidates: "అభ్యర్థులను తెలుసుకోండి",
    eci_portal_note: "గమనిక: ఈ లింకులు మిమ్మల్ని అధికారిక ECI పోర్టల్‌కు తీసుకెళ్తాయి.",
    no_match_title: "నేరుగా సరిపోలలేదు",
    no_match_subtitle: "మీరు దానిని అధికారిక ECI శోధన పోర్టల్‌లో కనుగొనవచ్చు.",
    go_to_official_search: "అధికారిక శోధన",
    welcome_back: "నమస్తే",
    welcome_subtitle: "మీ వ్యక్తిగతీకరించిన ఎన్నికల డాష్‌బోర్డ్‌కు స్వాగతం.",
    national_turnout: "జాతీయ ఓటింగ్ శాతం",
    total_votes_polled: "పోలైన మొత్తం ఓట్లు",
    status: "స్థితి",
    live_trend_analysis: "లైవ్ ట్రెండ్ అనాలిసిస్",
    election_timeline: "ఎన్నికల కాలక్రమం",
    live_results: "లైవ్ ఫలితాలు",
    need_help: "సహాయం కావాలా?",
    ai_help_desc: "ఓటింగ్ నియమాల గురించి మా AI సహాయకుడిని అడగండి.",
    start_chat: "చాట్ ప్రారంభించండి",
    know_candidates_desc: "అభ్యర్థుల ప్రొఫైల్‌లను సమీక్షించండి.",
    voter_search_desc: "ఓటర్ల జాబితాలో మీ పేరును తనిఖీ చేయండి.",
    voter_services_desc: "కొత్త ఓటరుగా నమోదు చేసుకోండి.",
    browse_list: "జాబితాను బ్రౌజ్ చేయండి",
    search_name: "పేరు వెతకండి",
    days: "రోజులు",
    hours: "గంటలు",
    minutes: "నిమిషాలు",
    seconds: "సెకన్లు",
    simulator_title: "ఓటు వేయడం ఎలా: EVM & VVPAT",
    simulator_desc: "ధృవీకరణ ప్రక్రియను అర్థం చేసుకోండి.",
    evm_unit: "EVM నియంత్రణ విభాగం",
    vvpat_verifier: "VVPAT వెరిఫైయర్",
    set_as_home: "హోమ్‌గా సెట్ చేయండి",
    start_journey: "ఓటరు ప్రయాణాన్ని ప్రారంభించండి",
    go_to_registration: "ఇప్పుడే నమోదు చేసుకోండి",
    verify_now: "ఐడిని ధృవీకరించండి",
    locate_booth: "బూత్‌ను కనుగొనండి",
    browse_candidates: "అభ్యర్థులను చూడండి",
    how_to_vote: "ట్యుటోరియల్ చూడండి",
    step_status_complete: "పూర్తయింది",
    step_status_pending: "చర్య అవసరం"
  },
  bn: {
    portal_name: "নির্বাচন পোর্টাল",
    election_dates: "নির্বাচনের তারিখ",
    voter_guide: "ভোটার গাইড",
    polling_stations: "ভোটকেন্দ্র",
    results: "ফলাফল",
    sign_in: "সাইন ইন",
    sign_up: "সাইন আপ",
    logout: "লগআউট",
    dashboard: "ড্যাশবোর্ড",
    voter_services: "ভোটার পরিষেবা",
    live_trends: "লাইভ ট্রেন্ডস",
    eci_resources: "ECI রিসোর্স",
    find_constituency: "নির্বাচনী এলাকা খুঁজুন",
    search_placeholder: "পিন বা নাম লিখুন...",
    lookup_btn: "খুঁজুন",
    chat_title: "ভারত নির্বাচন AI",
    chat_subtitle: "অফিসিয়াল সিভিক অ্যাসিস্ট্যান্ট",
    verified_eci: "ECI নথি দ্বারা যাচাইকৃত",
    ask_placeholder: "প্রশ্ন জিজ্ঞাসা করুন...",
    source_eci: "উৎস: ভারতের নির্বাচন কমিশন",
    days_to_election: "নির্বাচনের দিন বাকি",
    voting_reminders: "ভোটের রিমাইন্ডার পান",
    official_links: "অফিসিয়াল ECI লিঙ্ক",
    candidates: "প্রার্থী",
    vvpat_simulator: "VVPAT সিমুলেটর",
    verify_voter_id: "ভোটার আইডি যাচাই করুন",
    settings: "সেটিংস",
    support: "সহায়তা",
    language: "ভাষা",
    suggestion_1: "ভোটার হিসেবে নিবন্ধন করবেন কীভাবে?",
    suggestion_2: "আমার নির্বাচনী এলাকা কোনটি?",
    suggestion_3: "নয়া দিল্লিতে প্রার্থী কারা?",
    suggestion_4: "VVPAT মেশিন কী?",
    system_ready: "সিস্টেম প্রস্তুত",
    quick_enquiries: "দ্রুত অনুসন্ধান",
    chat_error: "দুঃখিত, সংযোগ করতে সমস্যা হচ্ছে।",
    verified_eci_title: "যাচাইকৃত ECI ডেটা",
    verified_eci_subtitle: "ভারতের নির্বাচন কমিশনের অফিসিয়াল পোর্টালে সরাসরি প্রবেশাধিকার।",
    official_integration: "অফিসিয়াল ইন্টিগ্রেশন",
    open_portal: "অফিসিয়াল পোর্টাল খুলুন",
    eci_disclaimer: "এখানে লিঙ্ক করা সমস্ত ডেটা সরাসরি ভারতের নির্বাচন কমিশন (ECI) থেকে নেওয়া হয়েছে।",
    res_voter_search_title: "ভোটার অনুসন্ধান",
    res_voter_search_desc: "ভোটার তালিকায় আপনার নাম খুঁজুন।",
    res_candidate_title: "আপনার প্রার্থীকে জানুন",
    res_candidate_desc: "প্রার্থীদের সম্পর্কে বিস্তারিত তথ্য।",
    res_education_title: "ভোটার শিক্ষা",
    res_education_desc: "ভোটদান প্রক্রিয়া সম্পর্কে জানুন।",
    res_results_title: "রিয়েল-টাইম ফলাফল",
    res_results_desc: "অফিসিয়াল নির্বাচন ফলাফল পোর্টাল দেখুন।",
    lookup_title: "আপনার নির্বাচনী এলাকা খুঁজুন",
    lookup_subtitle: "অফিসিয়াল প্রার্থী লিঙ্ক পেতে আপনার পিন বা নির্বাচনী এলাকার নাম লিখুন।",
    lookup_placeholder: "যেমন ১১০০০১ বা নতুন দিল্লি",
    constituency_suffix: "নির্বাচনী এলাকা",
    official_document: "অফিসিয়াল নথি",
    view_affidavits: "হলফনামা দেখুন",
    candidate_list: "প্রার্থী তালিকা",
    know_candidates: "প্রার্থীদের জানুন",
    eci_portal_note: "দ্রষ্টব্য: এই লিঙ্কগুলি আপনাকে অফিসিয়াল ECI পোর্টালে নিয়ে যাবে।",
    no_match_title: "সরাসরি মিল পাওয়া যায়নি",
    no_match_subtitle: "আপনি এটি অফিসিয়াল ECI অনুসন্ধান পোর্টালে খুঁজে পেতে পারেন।",
    go_to_official_search: "অফিসিয়াল অনুসন্ধান",
    welcome_back: "নমস্কার",
    welcome_subtitle: "আপনার ব্যক্তিগত নির্বাচন ড্যাশবোর্ডে আপনাকে স্বাগত জানাই।",
    national_turnout: "জাতীয় ভোটদানের হার",
    total_votes_polled: "মোট ভোট পড়েছে",
    status: "স্থিতি",
    live_trend_analysis: "লাইভ ট্রেন্ড বিশ্লেষণ",
    election_timeline: "নির্বাচনের সময়রেখা",
    live_results: "লাইভ ফলাফল",
    need_help: "সাহায্য প্রয়োজন?",
    ai_help_desc: "ভোটের নিয়ম সম্পর্কে আমাদের AI সহকারীকে জিজ্ঞাসা করুন।",
    start_chat: "চ্যাট শুরু করুন",
    know_candidates_desc: "প্রার্থীদের প্রোফাইল পর্যালোচনা করুন।",
    voter_search_desc: "ভোটার তালিকায় আপনার নাম পরীক্ষা করুন।",
    voter_services_desc: "নতুন ভোটার হিসেবে নিবন্ধন করুন।",
    browse_list: "তালিকা দেখুন",
    search_name: "নাম খুঁজুন",
    days: "দিন",
    hours: "ঘণ্টা",
    minutes: "মিনিট",
    seconds: "সেকেন্ড",
    simulator_title: "ভোট দেবেন কীভাবে: EVM ও VVPAT",
    simulator_desc: "যাচাইকরণ প্রক্রিয়াটি বুঝুন।",
    evm_unit: "EVM কন্ট্রোল ইউনিট",
    vvpat_verifier: "VVPAT ভেরিফায়ার",
    set_as_home: "হোম হিসেবে সেট করুন",
    start_journey: "ভোটার যাত্রা শুরু করুন",
    go_to_registration: "এখনই নিবন্ধন করুন",
    verify_now: "আইডি যাচাই করুন",
    locate_booth: "বুথ খুঁজুন",
    browse_candidates: "প্রার্থী দেখুন",
    how_to_vote: "টিউটোরিয়াল দেখুন",
    step_status_complete: "সম্পন্ন",
    step_status_pending: "পদক্ষেপ প্রয়োজন"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['en', 'hi', 'ta', 'te', 'bn'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
